package com.shinowit.dao.mapper;

import com.shinowit.model.Province;
import com.shinowit.model.ProvinceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    int countByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    int deleteByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    List<Province> selectByExample(ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table province
     *
     * @mbggenerated Mon Jan 12 16:37:12 CST 2015
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceCriteria example);
}