package com.shinowit.dao.mapper;

import com.shinowit.model.TauOperinfo;
import com.shinowit.model.TauOperinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TauOperinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int countByExample(TauOperinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int deleteByExample(TauOperinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int deleteByPrimaryKey(String operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int insert(TauOperinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int insertSelective(TauOperinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    List<TauOperinfo> selectByExample(TauOperinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    TauOperinfo selectByPrimaryKey(String operid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") TauOperinfo record, @Param("example") TauOperinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByExample(@Param("record") TauOperinfo record, @Param("example") TauOperinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByPrimaryKeySelective(TauOperinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_OperInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByPrimaryKey(TauOperinfo record);
}