package com.shinowit.dao.mapper;

import com.shinowit.model.TauRoleinfo;
import com.shinowit.model.TauRoleinfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TauRoleinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int countByExample(TauRoleinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int deleteByExample(TauRoleinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int deleteByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int insert(TauRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int insertSelective(TauRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    List<TauRoleinfo> selectByExample(TauRoleinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    TauRoleinfo selectByPrimaryKey(String roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByExampleSelective(@Param("record") TauRoleinfo record, @Param("example") TauRoleinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByExample(@Param("record") TauRoleinfo record, @Param("example") TauRoleinfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByPrimaryKeySelective(TauRoleinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TAu_RoleInfo
     *
     * @mbggenerated Thu Dec 25 18:54:52 CST 2014
     */
    int updateByPrimaryKey(TauRoleinfo record);
}